#                                                           Developed by Sxmuray
#                                                     (Aquatic Studios @ (C) 2019-2022)

name: 'JoinEffects'
version: '1.3'
authors:
  - 'Sxmuray'
  - 'Aquatic Studios'

main: org.github.sxmuray.JoinEffects
website: https://github.com/Sxmuray

description: 'All rights reserved by Aquatic Studios'

commands:
  joineffects:
    description: "Plugin main command"
  effects:
    description: "Command to open the menu"
